# Generated by Django 5.1.3 on 2024-12-01 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time1', models.DateTimeField()),
                ('time2', models.DateTimeField()),
                ('temperature_max', models.FloatField()),
                ('temperature_min', models.FloatField()),
                ('humidity_max', models.FloatField()),
                ('humidity_min', models.FloatField()),
                ('lux_level_max', models.FloatField()),
                ('lux_level_min', models.FloatField()),
                ('soil_moisture_max', models.FloatField()),
                ('soil_moisture_min', models.FloatField()),
                ('co2_max', models.FloatField()),
                ('co2_min', models.FloatField()),
            ],
        ),
    ]
